name: flutter_movie_app
description: A Flutter movie information app using TMDB API.
version: 1.0.0
environment:
  sdk: '>=3.0.0 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.5
  permission_handler: ^11.3.1
  flutter_dotenv: ^5.0.2
  flutter_riverpod: ^2.6.1
  equatable: ^2.0.5
  dartz: ^0.10.1
dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.3.2
flutter:
  assets:
    - .env
  uses-material-design: true
